### PR TITLE
Update Spools in UI on API call

### PR DESCRIPTION
**Pull request by oschwartz10612**
Allows a client to update the ui when inserting or selecting spools. Previously a reload of the page was required.

Example api call:
```
url = 'http://localhost/plugin/filamentmanager/selections/0'
    headers = {'X-Api-Key': config.API_KEY}
    payload = {
        "selection": {
            "tool": 0, 
            "spool": {
                "id": id
            }   
        },
        "update": True
    }
```

The `update:True` is required to prevent normal calls from unnecessarily updating.

I am using this in my [project here](https://github.com/oschwartz10612/Filament-Manager-Barcodes) to update spools when scanned with a barcode scanner.

### CODE REVIEW

**Comment by oschwartz10612** [comment]
@OllisGit Any chance you want to take a look before Mr. Stale closes my request?

**Comment by OllisGit** [comment]
Hi @oschwartz10612 ,

thanks for the PR. I would like to implement your PR with a small change.

Instead of the keyword ```update``` (in the payload) I would like to use the more precise word ```notifyclient``` or ```updateui```.

What do you think?

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by oschwartz10612** [comment]
Hi! 

No problem, it is important to take breaks!

I think you are correct. `updateui ` is more explicit and will reduce confusion. I already made the change.

Is there anything else you would like to see changed? 

Thanks for your work on the project!

**Comment by OllisGit** [comment]
Hi @oschwartz10612,
you PR was not working! Now it is fixed and will be in the next release.

**Comment by oschwartz10612** [comment]
I believe I fixed the conflict. Let me know if it is unsatisfactory.

**Comment by OllisGit** [comment]
Release 1.7.0 is out. 
Please test and give a feedback via issue tracker if you receive an error.

**Pull request closed without merging**
